// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeColumnsTableIpdVitalSignForAdult_V1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeColumnsTableIpdVitalSignForAdult_V1));
        
        string IMigrationMetadata.Id
        {
            get { return "202201041109279_changeColumnsTableIpdVitalSignForAdult_V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
